---
driver:
  name: vagrant

platforms:
  - name: mac-os-x-yosemite
  - name: mac-os-x-el-capitan
  - name: mac-os-x-sierra
  - name: mac-os-x-high-sierra
  - name: mac-os-x-mojave
  - name: mac-os-x-catalina

suites:
  - name: application
    run_list: test::application
  - name: framework
    run_list: test::framework
